### ISSUE TITLE
Uncaught error for missing operation

### ISSUE THREAD

**Issue by johnbeech** [anttiviljami/openapi-client-axios#150]
Uncaught error for missing operation.

Run command:
```
typegen tests/post-deployment/downloaded-appStore-openapi.json
```

Direct error for my input:
```
/workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:80
    key = key.replace(/\/(.)/g, function (_match, p1) {
              ^

TypeError: Cannot read properties of undefined (reading 'replace')
    at convertKeyToTypeName (/workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:80:15)
    at generateMethodForOperation (/workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:172:33)
    at /workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:218:16
    at Array.map (<anonymous>)
    at generateOperationMethodTypings (/workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:217:39)
    at /workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:152:40
    at step (/workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:52:23)
    at Object.next (/workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:33:53)
    at fulfilled (/workspace/src/project/node_modules/openapi-client-axios-typegen/typegen.js:24:58)
```

Context: trying to generate a typescript definition for a generated Amazon API Gateway Open API doc instance (using [GetExport](https://docs.aws.amazon.com/apigateway/latest/api/API_GetExport.html)).

```sh
node_modules/openapi-client-axios-typegen/typegen.js:80
    key = key.replace(/\/(.)/g, function (_match, p1) {
              ^
TypeError: Cannot read properties of undefined (reading 'replace')
```

```js
function convertKeyToTypeName(key) {
    key = key.replace(/\/(.)/g, function (_match, p1) {
        return p1.toUpperCase();
    });
    return key
        .replace(/}/g, '')
        .replace(/{/g, '$')
        .replace(/^\//, '')
        .replace(/[^0-9A-Za-z_$]+/g, '_');
}
```

Stepping up, methodName / operation are empty:

```js
function generateMethodForOperation(methodName, operation, exportTypes) {
    var operationId = operation.operationId, summary = operation.summary, description = operation.description;
    // parameters arg
    console.log('Generating for:', { methodName, operationId })
    var normalizedOperationId = convertKeyToTypeName(operationId);
```

```
Generating for: { methodName: 'getConfigSchema', operationId: 'getConfigSchema' }
Generating for: { methodName: 'putConfigSchema', operationId: 'putConfigSchema' }
Generating for: { methodName: undefined, operationId: undefined }
```

Stepping up again, logged out operations:

```js
function generateOperationMethodTypings(api, exportTypes, opts) {
    var operations = api.getOperations();
    console.log('Operations:', { operations })
    var operationTypings = operations.map(function (op) {
        return generateMethodForOperation(opts.transformOperationName(op.operationId), op, exportTypes);
    });
...
```

```
Operations: {
  operations: [
    {
      operationId: 'getConfigSchema',
      parameters: [Array],
      responses: [Object],
      security: [Array],
      path: '/apps/{appId}/versions/{appVersion}/config-schema',
      method: 'get'
    },
    {
      operationId: 'putConfigSchema',
      parameters: [Array],
      requestBody: [Object],
      responses: [Object],
      security: [Array],
      path: '/apps/{appId}/versions/{appVersion}/config-schema',
      method: 'put'
    },
    {
      parameters: [Array],
      responses: [Object],
      path: '/apps/{appId}/versions/{appVersion}/config-schema',
      method: 'options',
      security: undefined
    },
    {
      operationId: 'getStatus',
      responses: [Object],
      security: [Array],
      path: '/status',
      method: 'get'
    },
    {
      responses: [Object],
      path: '/status',
      method: 'options',
      security: undefined
    },
    {
      operationId: 'listApps',
      responses: [Object],
      security: [Array],
      path: '/apps',
      method: 'get'
    },
    {
      operationId: 'registerApp',
      responses: [Object],
      security: [Array],
      path: '/apps',
      method: 'post'
    },
    {
      responses: [Object],
      path: '/apps',
      method: 'options',
      security: undefined
    },
    {
      parameters: [Array],
      responses: [Object],
      path: '/apps/{appId}',
      method: 'options',
      security: undefined
    },
    {
      operationId: 'listAppVersions',
      parameters: [Array],
      responses: [Object],
      security: [Array],
      path: '/apps/{appId}/versions',
      method: 'get'
    },
    {
      parameters: [Array],
      responses: [Object],
      path: '/apps/{appId}/versions',
      method: 'options',
      security: undefined
    },
    {
      operationId: 'getAppVersionDetails',
      parameters: [Array],
      responses: [Object],
      security: [Array],
      path: '/apps/{appId}/versions/{appVersion}',
      method: 'get'
    },
    {
      parameters: [Array],
      responses: [Object],
      path: '/apps/{appId}/versions/{appVersion}',
      method: 'options',
      security: undefined
    },
    {
      operationId: 'getOpenAPISpec',
      responses: [Object],
      security: [Array],
      path: '/openapi',
      method: 'get'
    },
    {
      responses: [Object],
      path: '/openapi',
      method: 'options',
      security: undefined
    },
    {
      responses: [Object],
      path: '/',
      method: 'options',
      security: undefined
    }
  ]
```

It appears the one it fails on is the CORS `options` request `put`, and `get` blocks processed fine:
```
    {
      parameters: [Array],
      responses: [Object],
      path: '/apps/{appId}/versions/{appVersion}/config-schema',
      method: 'options',
      security: undefined
    }
 ```
 
Partial JSON to help reproduce the issue: 
 ```json
 {
  "paths": {
    "/apps/{appId}/versions/{appVersion}/config-schema": {
      "get": {
        "operationId": "getConfigSchema",
        "parameters": [
          {
            "name": "appId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "appVersion",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "200 response",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Credentials": {
                "schema": {
                  "type": "string"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StubModel"
                }
              }
            }
          }
        },
        "security": [
          {
            "abc123": []
          }
        ]
      },
      "put": {
        "operationId": "putConfigSchema",
        "parameters": [
          {
            "name": "appId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "appVersion",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "content": {
            "application/json": {
              "schema": {
                "$ref": "#/components/schemas/StubModel"
              }
            }
          },
          "required": true
        },
        "responses": {
          "200": {
            "description": "200 response",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Credentials": {
                "schema": {
                  "type": "string"
                }
              },
              "Content-Type": {
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {
              "application/json": {
                "schema": {
                  "$ref": "#/components/schemas/StubModel"
                }
              }
            }
          }
        },
        "security": [
          {
            "abc123": []
          }
        ]
      },
      "options": {
        "parameters": [
          {
            "name": "appId",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "appVersion",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "204": {
            "description": "204 response",
            "headers": {
              "Access-Control-Allow-Origin": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Methods": {
                "schema": {
                  "type": "string"
                }
              },
              "Vary": {
                "schema": {
                  "type": "string"
                }
              },
              "Access-Control-Allow-Headers": {
                "schema": {
                  "type": "string"
                }
              }
            },
            "content": {}
          }
        }
      }
    }
  }
}
```

I think I can fix the error locally by ignoring operations that don't have the necessary fields.

**Comment by anttiviljami** [comment]
Hi @johnbeech! Would you care submitting a PR with your changes? 🙏

**Comment by johnbeech** [comment]
Created https://github.com/anttiviljami/openapi-client-axios/pull/152 for review! 🌻
