### ISSUE TITLE
`typegen` command reads file from `node_modules\@apidevtools\json-schema-ref-parser\dist` directory

### ISSUE THREAD

**Issue by dzikoysk** [anttiviljami/openapi-client-axios#167]
Docs references that definition can be read from file located in project dir:

`typegen ./openapi.yml > client.d.ts  - generate a type definition file`

Unfortunately, it's not the case 7.3.2:

```
$ typegen xxx.json > src/types/openapi.d.ts

node:internal/process/promises:288
            triggerUncaughtException(err, true /* fromPromise */);
            ^

JSONParserError: Error opening file "P:\xxx\xxx-frontend\node_modules\@apidevtools\json-schema-ref-parser\dist\xxx.json"
ENOENT: no such file or directory, open 'P:\xxx\xxx-frontend\node_modules\@apidevtools\json-schema-ref-parser\dist\xxx.json'        
    at Object.<anonymous> (P:\xxx\xxx-frontend\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\resolvers\file.js:72:23)        
    at Generator.throw (<anonymous>)
    at rejected (P:\xxx\xxx-frontend\node_modules\@apidevtools\json-schema-ref-parser\dist\lib\resolvers\file.js:29:65) {
  code: 'ERESOLVER',
  name: 'ResolverError',
  source: 'P:\\xxx\\xxx-frontend\\node_modules\\@apidevtools\\json-schema-ref-parser\\dist\\xxx.json',
  path: null,
  toJSON: [Function: toJSON],
  ioErrorCode: 'ENOENT',
  [Symbol(nodejs.util.inspect.custom)]: [Function: inspect]
}
```

I've replaced it with the following command and it works:

```
$ curl http://localhost:8080/v3/api-docs > node_modules/@apidevtools/json-schema-ref-parser/dist/xxx.json && typegen xxx.json > src/types/openapi.d.ts"
```

But it doesn't seems to be right. Am I missing something or it's just a bug?

**Comment by bzp99** [comment]
I just discovered the same. You can give an absolute path to `typegen` instead of placing the spec in the `node_modules` directory. This is most definitely a bug IMO, but I cannot afford to look into what causes it at the moment.

**Comment by pcolot01** [comment]
After investigation, I understood ref is a powerful mechanism to connect to remote, local resources or even database,  ...
The ref problem is to identify the exact context local, remote, ... 
So I just force the file protocol with a local reference. And it works.

The solution:

$ref: 'file:./BlackmagicTransportControlComponent.yaml#/components/pathitems/transports.0'

The errors:

$ref: './BlackmagicTransportControlComponent.yaml#/components/pathitems/transports.0'
is local to the typgen mode

$ref: '/BlackmagicTransportControlComponent.yaml#/components/pathitems/transports.0'
is using an absolute path from the root


Best
